//! Render an encoded [`crate::vm::Module`] as a self-contained Luau script
//! that decrypts (Phase 2+) and interprets the embedded bytecode.

mod runtime;

use crate::vm::{Const, Module};
use crate::ProtectOptions;

pub fn render(module: &Module, opts: &ProtectOptions) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by luau-protect v");
    out.push_str(crate::VERSION);
    out.push_str("\n-- DO NOT EDIT — recompile from source instead.\n\n");

    // RNG for Phase 7A numeric obfuscation. Seeded from opts.seed so builds
    // are reproducible.
    let mut num_state: u32 = opts
        .seed
        .map(|s| (s as u32) ^ 0x517C_C1B7)
        .unwrap_or(0x517C_C1B7);
    if num_state == 0 {
        num_state = 1;
    }

    // Constant table.
    out.push_str("local _C = {");
    for (i, c) in module.constants.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        match c {
            Const::Number(n) => {
                if opts.obfuscate_numbers {
                    out.push_str(&format_number_obfuscated(*n, &mut num_state));
                } else {
                    out.push_str(&format_number(*n));
                }
            }
            Const::String(b) => {
                if opts.lazy_strings {
                    // Wrap encrypted ciphertext in a 1-element table so the
                    // dispatcher's PushConst can detect "not yet decrypted"
                    // by type-checking for `table`.
                    out.push_str("{\"");
                    out.push_str(&escape_lua_string_bytes(b));
                    out.push_str("\"}");
                } else {
                    out.push('"');
                    out.push_str(&escape_lua_string_bytes(b));
                    out.push('"');
                }
            }
        }
    }
    out.push_str("}\n");

    // Protos.
    out.push_str("local _P = {");
    for (i, p) in module.protos.iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push_str("{c=\"");
        out.push_str(&escape_lua_string_bytes(&p.code));
        out.push_str("\",np=");
        out.push_str(&p.num_params.to_string());
        out.push_str(",nl=");
        out.push_str(&p.num_locals.to_string());
        out.push_str(",nu=");
        out.push_str(&p.num_upvalues.to_string());
        out.push_str(",va=");
        out.push_str(if p.is_vararg { "true" } else { "false" });
        out.push_str(",k=");
        out.push_str(&p.operand_key.to_string());
        out.push('}');
    }
    out.push_str("}\n\n");

    // Common helpers (bit32 aliases + xs32) — always emitted; used by both
    // the decrypt bootstrap and the dispatcher's operand-key derivation.
    out.push_str(runtime::COMMON_HELPERS);

    // Optional decryption bootstrap (Phase 2).
    if let Some(seed) = module.encryption_seed {
        out.push_str(runtime::DECRYPT_BOOTSTRAP);
        out.push_str(&format!("\n_decrypt_module({})\n\n", seed));
    }

    // Runtime dispatcher: Phase 5 hands us a permutation; otherwise identity.
    let perm = module.opcode_perm.unwrap_or_else(runtime::identity_perm);
    out.push_str(&runtime::build_dispatcher(&perm));
    out.push_str("\n\n");

    // Bootstrap: invoke main proto with script args.
    out.push_str("return _exec(0, {...}, nil)\n");

    let _ = opts;
    out
}

fn format_number(n: f64) -> String {
    if n.is_nan() {
        return "(0/0)".into();
    }
    if n.is_infinite() {
        return if n > 0.0 { "(1/0)".into() } else { "(-1/0)".into() };
    }
    if n == n.trunc() && n.abs() < 1e16 {
        return format!("{}", n as i64);
    }
    format!("{n}")
}

/// Render a number as an opaque Lua expression so the literal value never
/// appears in the output. Integers fitting in u32 become `bit32.bxor(A, B)`
/// with A random and B = A ^ N. Larger integers split additively. Non-integer
/// floats fall back to the literal form (they're rare in obfuscation-relevant
/// scripts and `bit32` only handles 32-bit operands).
fn format_number_obfuscated(n: f64, state: &mut u32) -> String {
    if n.is_nan() {
        return "(0/0)".into();
    }
    if n.is_infinite() {
        return if n > 0.0 { "(1/0)".into() } else { "(-1/0)".into() };
    }
    // Non-integer floats: leave as literal. They don't carry the semantic
    // signal that string literals or hard-coded thresholds do.
    if n != n.trunc() {
        return format!("{n}");
    }
    let abs = n.abs();

    // u32 range: cleanest path, single bit32.bxor expression.
    if abs < (1u64 << 31) as f64 {
        let val = n as i64;
        let target = if val < 0 {
            // Use absolute value in the XOR, negate the expression.
            (-val) as u32
        } else {
            val as u32
        };
        *state = xs32(*state);
        let key = *state;
        let other = target ^ key;
        let core = format!("bit32.bxor({key},{other})");
        return if val < 0 { format!("(-{core})") } else { core };
    }

    // Larger integers: additive split (no bit32 wrap concerns).
    let val = n as i64;
    *state = xs32(*state);
    let r = (*state as i32) as i64;
    let lhs = val - r;
    let rhs = r;
    if rhs >= 0 {
        format!("({lhs}+{rhs})")
    } else {
        format!("({lhs}{rhs})")
    }
}

fn xs32(mut s: u32) -> u32 {
    s ^= s << 13;
    s ^= s >> 17;
    s ^= s << 5;
    s
}

/// Escape a byte sequence into a Lua string literal: printable ASCII (except
/// quotes/backslash) emits raw, everything else uses 3-digit decimal escapes
/// to avoid ambiguity with following digits.
pub fn escape_lua_string_bytes(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len());
    for &b in bytes {
        match b {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\r' => out.push_str("\\r"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7E => out.push(b as char),
            _ => {
                out.push('\\');
                out.push_str(&format!("{:03}", b));
            }
        }
    }
    out
}
